name: Price Monitor

on:
  schedule:
    - cron: '*/30 * * * *'   # каждые 30 минут
  workflow_dispatch:

jobs:
  check_price:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run price parser
        run: python tests/test_parser_ps5_slim.py   # путь к файлу внутри папки tests
